/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lat1;

import javax.swing.JLabel;

/**
 *
 * @author HP
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2(String nm, String abs, String kls, String jrs, String almt) {       
        initComponents();
        hasil1.setText(nm);
        hasil2.setText(abs);
        hasil3.setText(kls);
        hasil4.setText(jrs);
        hasil5.setText(almt);
    }

    

    

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JLabel();
        hasil2 = new javax.swing.JLabel();
        hasil3 = new javax.swing.JLabel();
        hasil4 = new javax.swing.JLabel();
        hasil5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hasil Biodata");

        hasil1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hasil1.setText("Hasil 1");

        hasil2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hasil2.setText("Hasil 2");

        hasil3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hasil3.setText("Hasil 3");

        hasil4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hasil4.setText("Hasil 4");

        hasil5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hasil5.setText("Hasil 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasil1)
                            .addComponent(hasil2)
                            .addComponent(hasil3)
                            .addComponent(hasil4)
                            .addComponent(hasil5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasil1)
                .addGap(18, 18, 18)
                .addComponent(hasil2)
                .addGap(18, 18, 18)
                .addComponent(hasil3)
                .addGap(18, 18, 18)
                .addComponent(hasil4)
                .addGap(18, 18, 18)
                .addComponent(hasil5)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hasil1;
    private javax.swing.JLabel hasil2;
    private javax.swing.JLabel hasil3;
    private javax.swing.JLabel hasil4;
    private javax.swing.JLabel hasil5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
